{% set name = "PDFstream" %}
{% set version = "0.3.2" %}
{% set sha256 = "191db6aa458d57881c0fad53cb2c540153deaa6e3072ea8c37b91bd88fd68659" %}
{% set org = "xpdAcq" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bluesky
    - databroker
    - fire
    - numba
    - pyfai
    - scikit-beam
    - suitcase-csv
    - suitcase-json-metadata
    - suitcase-tiff
    - xpdview
    - xray-vision

test:
  imports:
    - pdfstream
    - pdfstream.integration
    - pdfstream.transformation
    - pdfstream.utils
    - pdfstream.vend
    - pdfstream.visualization
  commands:
    - pdfstream -- --help

about:
  home: https://github.com/{{ org }}/pdfstream
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The data analysis toolbox for the study on pair distribution function (PDF).
